import { Kysely, sql } from 'kysely';
import { Database, NewPlantLibrary } from '../types';

const plantLibrarySeed: NewPlantLibrary[] = [
  {
    commonName: 'Tomato',
    botanicalName: 'Solanum lycopersicum',
    plantCategory: 'vegetable',
    waterNeed: 'high',
    waterNotes: 'Keep soil evenly moist with deep watering 2 to 3 times per week.',
    sunNeed: 'full_sun',
    sunNotes: 'Needs at least 6 to 8 hours of direct sun.',
    nutritionNeed: 'high',
    nutritionNotes: 'Add compost at planting, then feed every 2 to 3 weeks after first fruit set.',
    plantingNotes: 'Plant deeply and stake or cage early.',
    spacingCm: 60,
    daysToMaturity: 75,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Basil',
    botanicalName: 'Ocimum basilicum',
    plantCategory: 'herb',
    waterNeed: 'moderate',
    waterNotes: 'Water when the top 2 cm of soil feels dry.',
    sunNeed: 'full_sun',
    sunNotes: 'Best with 6 hours of sun and some afternoon protection in hot weather.',
    nutritionNeed: 'low',
    nutritionNotes: 'Use light compost at planting; avoid heavy feeding to preserve flavor.',
    plantingNotes: 'Pinch tips often to keep plants bushy.',
    spacingCm: 25,
    daysToMaturity: 60,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Lettuce',
    botanicalName: 'Lactuca sativa',
    plantCategory: 'vegetable',
    waterNeed: 'moderate',
    waterNotes: 'Keep soil consistently moist, especially in warm spells.',
    sunNeed: 'partial_sun',
    sunNotes: 'Prefers morning sun and light afternoon shade in summer.',
    nutritionNeed: 'moderate',
    nutritionNotes: 'Add compost before planting and a nitrogen-rich feed after 3 weeks.',
    plantingNotes: 'Succession sow every 2 weeks for steady harvests.',
    spacingCm: 25,
    daysToMaturity: 45,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Cucumber',
    botanicalName: 'Cucumis sativus',
    plantCategory: 'vegetable',
    waterNeed: 'high',
    waterNotes: 'Water deeply and consistently; drought can make fruit bitter.',
    sunNeed: 'full_sun',
    sunNotes: 'Needs 6 to 8 hours of direct sun.',
    nutritionNeed: 'high',
    nutritionNotes: 'Mix compost before planting and feed when vines begin flowering.',
    plantingNotes: 'Grow on a trellis to save space and improve airflow.',
    spacingCm: 45,
    daysToMaturity: 60,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Bell Pepper',
    botanicalName: 'Capsicum annuum',
    plantCategory: 'vegetable',
    waterNeed: 'moderate',
    waterNotes: 'Water evenly; avoid letting soil fully dry out.',
    sunNeed: 'full_sun',
    sunNotes: 'Needs warm soil and 6 or more hours of sun.',
    nutritionNeed: 'moderate',
    nutritionNotes: 'Add compost at planting and feed lightly when flowers appear.',
    plantingNotes: 'Stake heavily loaded plants.',
    spacingCm: 45,
    daysToMaturity: 75,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Carrot',
    botanicalName: 'Daucus carota subsp. sativus',
    plantCategory: 'vegetable',
    waterNeed: 'moderate',
    waterNotes: 'Keep seedbed moist until germination, then water deeply weekly.',
    sunNeed: 'full_sun',
    sunNotes: 'Full sun gives best roots, partial sun is tolerated.',
    nutritionNeed: 'low',
    nutritionNotes: 'Avoid fresh manure and excess nitrogen; loosen soil before sowing.',
    plantingNotes: 'Thin seedlings early for straight roots.',
    spacingCm: 5,
    daysToMaturity: 70,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Strawberry',
    botanicalName: 'Fragaria x ananassa',
    plantCategory: 'fruit',
    waterNeed: 'moderate',
    waterNotes: 'Water regularly during flowering and fruiting.',
    sunNeed: 'full_sun',
    sunNotes: 'Best fruit production with 6 to 8 hours of sun.',
    nutritionNeed: 'moderate',
    nutritionNotes: 'Add compost at planting and feed after harvest to support next season.',
    plantingNotes: 'Keep crowns just above soil level.',
    spacingCm: 30,
    daysToMaturity: null,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Zucchini',
    botanicalName: 'Cucurbita pepo',
    plantCategory: 'vegetable',
    waterNeed: 'high',
    waterNotes: 'Water deeply at soil level 2 or more times per week in dry weather.',
    sunNeed: 'full_sun',
    sunNotes: 'Needs full sun for steady fruiting.',
    nutritionNeed: 'high',
    nutritionNotes: 'Add compost before planting and feed when flowering starts.',
    plantingNotes: 'Give each plant plenty of room for airflow.',
    spacingCm: 90,
    daysToMaturity: 50,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Green Bean',
    botanicalName: 'Phaseolus vulgaris',
    plantCategory: 'vegetable',
    waterNeed: 'moderate',
    waterNotes: 'Water during flowering and pod formation.',
    sunNeed: 'full_sun',
    sunNotes: 'Needs at least 6 hours of direct sun.',
    nutritionNeed: 'low',
    nutritionNotes: 'Avoid excess nitrogen; compost before sowing is usually enough.',
    plantingNotes: 'Provide support for pole varieties.',
    spacingCm: 15,
    daysToMaturity: 55,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Pea',
    botanicalName: 'Pisum sativum',
    plantCategory: 'vegetable',
    waterNeed: 'moderate',
    waterNotes: 'Keep evenly moist during flowering and pod fill.',
    sunNeed: 'partial_sun',
    sunNotes: 'Cool-season crop; full sun in spring, light shade as days warm.',
    nutritionNeed: 'low',
    nutritionNotes: 'Compost before sowing is enough; avoid high nitrogen fertilizer.',
    plantingNotes: 'Use a trellis for climbing types.',
    spacingCm: 8,
    daysToMaturity: 65,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Spinach',
    botanicalName: 'Spinacia oleracea',
    plantCategory: 'vegetable',
    waterNeed: 'moderate',
    waterNotes: 'Keep soil moist for tender leaves.',
    sunNeed: 'partial_sun',
    sunNotes: 'Best in cool weather with morning sun.',
    nutritionNeed: 'moderate',
    nutritionNotes: 'Add compost before sowing and a light nitrogen feed after cutting.',
    plantingNotes: 'Sow in spring or late summer.',
    spacingCm: 15,
    daysToMaturity: 40,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Kale',
    botanicalName: 'Brassica oleracea var. sabellica',
    plantCategory: 'vegetable',
    waterNeed: 'moderate',
    waterNotes: 'Water consistently for tender growth.',
    sunNeed: 'full_sun',
    sunNotes: 'Full sun is best; tolerates partial shade.',
    nutritionNeed: 'moderate',
    nutritionNotes: 'Add compost before planting and feed monthly during active growth.',
    plantingNotes: 'Harvest outer leaves first.',
    spacingCm: 45,
    daysToMaturity: 55,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Potato',
    botanicalName: 'Solanum tuberosum',
    plantCategory: 'vegetable',
    waterNeed: 'moderate',
    waterNotes: 'Water steadily during tuber formation; reduce near harvest.',
    sunNeed: 'full_sun',
    sunNotes: 'Needs at least 6 hours of sun.',
    nutritionNeed: 'moderate',
    nutritionNotes: 'Add compost at planting and side-dress when hilling.',
    plantingNotes: 'Hill soil around stems as plants grow.',
    spacingCm: 35,
    daysToMaturity: 100,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Onion',
    botanicalName: 'Allium cepa',
    plantCategory: 'vegetable',
    waterNeed: 'moderate',
    waterNotes: 'Water regularly while bulbs size up; reduce before harvest.',
    sunNeed: 'full_sun',
    sunNotes: 'Needs full sun for large bulbs.',
    nutritionNeed: 'moderate',
    nutritionNotes: 'Feed with nitrogen early, then stop once bulbs begin swelling.',
    plantingNotes: 'Keep weed pressure low around shallow roots.',
    spacingCm: 12,
    daysToMaturity: 100,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Garlic',
    botanicalName: 'Allium sativum',
    plantCategory: 'vegetable',
    waterNeed: 'moderate',
    waterNotes: 'Water in spring; stop watering when leaves start yellowing.',
    sunNeed: 'full_sun',
    sunNotes: 'Needs full sun and well-drained soil.',
    nutritionNeed: 'moderate',
    nutritionNotes: 'Add compost at planting and feed once in early spring.',
    plantingNotes: 'Plant cloves in fall in many climates.',
    spacingCm: 15,
    daysToMaturity: 240,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Rosemary',
    botanicalName: 'Salvia rosmarinus',
    plantCategory: 'herb',
    waterNeed: 'low',
    waterNotes: 'Let soil dry between waterings.',
    sunNeed: 'full_sun',
    sunNotes: 'Needs bright sun and excellent drainage.',
    nutritionNeed: 'low',
    nutritionNotes: 'Avoid rich feeding; compost once in spring if growth is weak.',
    plantingNotes: 'Grow in a raised bed or pot if soil stays wet.',
    spacingCm: 60,
    daysToMaturity: null,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Thyme',
    botanicalName: 'Thymus vulgaris',
    plantCategory: 'herb',
    waterNeed: 'low',
    waterNotes: 'Water sparingly once established.',
    sunNeed: 'full_sun',
    sunNotes: 'Full sun produces compact, flavorful growth.',
    nutritionNeed: 'low',
    nutritionNotes: 'Needs little feeding; add light compost in spring only if needed.',
    plantingNotes: 'Trim after flowering to keep plants dense.',
    spacingCm: 25,
    daysToMaturity: null,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Mint',
    botanicalName: 'Mentha spp.',
    plantCategory: 'herb',
    waterNeed: 'high',
    waterNotes: 'Keep soil moist, especially in containers.',
    sunNeed: 'partial_sun',
    sunNotes: 'Morning sun with afternoon shade is ideal.',
    nutritionNeed: 'low',
    nutritionNotes: 'Compost in spring is enough; excess feeding reduces flavor.',
    plantingNotes: 'Grow in a container to control spreading.',
    spacingCm: 45,
    daysToMaturity: 60,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Parsley',
    botanicalName: 'Petroselinum crispum',
    plantCategory: 'herb',
    waterNeed: 'moderate',
    waterNotes: 'Keep evenly moist for steady leaf growth.',
    sunNeed: 'partial_sun',
    sunNotes: 'Full sun in cool weather, partial shade in heat.',
    nutritionNeed: 'moderate',
    nutritionNotes: 'Add compost at planting and feed lightly every 4 to 6 weeks.',
    plantingNotes: 'Harvest outer stems from the base.',
    spacingCm: 20,
    daysToMaturity: 75,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Cilantro',
    botanicalName: 'Coriandrum sativum',
    plantCategory: 'herb',
    waterNeed: 'moderate',
    waterNotes: 'Keep soil evenly moist to slow bolting.',
    sunNeed: 'partial_sun',
    sunNotes: 'Prefers cool weather and light afternoon shade.',
    nutritionNeed: 'low',
    nutritionNotes: 'Compost before sowing is usually enough.',
    plantingNotes: 'Succession sow often because plants bolt quickly.',
    spacingCm: 15,
    daysToMaturity: 45,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Oregano',
    botanicalName: 'Origanum vulgare',
    plantCategory: 'herb',
    waterNeed: 'low',
    waterNotes: 'Let soil dry between waterings.',
    sunNeed: 'full_sun',
    sunNotes: 'Full sun develops strongest flavor.',
    nutritionNeed: 'low',
    nutritionNotes: 'Avoid heavy feeding; trim and add light compost in spring.',
    plantingNotes: 'Cut back after flowering.',
    spacingCm: 30,
    daysToMaturity: null,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Lavender',
    botanicalName: 'Lavandula angustifolia',
    plantCategory: 'flower',
    waterNeed: 'low',
    waterNotes: 'Water to establish, then keep on the dry side.',
    sunNeed: 'full_sun',
    sunNotes: 'Needs full sun and sharp drainage.',
    nutritionNeed: 'low',
    nutritionNotes: 'Do not overfertilize; add grit or compost only if soil is poor.',
    plantingNotes: 'Prune lightly after bloom.',
    spacingCm: 45,
    daysToMaturity: null,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Sunflower',
    botanicalName: 'Helianthus annuus',
    plantCategory: 'flower',
    waterNeed: 'moderate',
    waterNotes: 'Water deeply, especially while buds form.',
    sunNeed: 'full_sun',
    sunNotes: 'Needs 6 to 8 hours of sun.',
    nutritionNeed: 'moderate',
    nutritionNotes: 'Add compost before planting; feed tall varieties once during rapid growth.',
    plantingNotes: 'Stake tall types in windy areas.',
    spacingCm: 45,
    daysToMaturity: 85,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Marigold',
    botanicalName: 'Tagetes spp.',
    plantCategory: 'flower',
    waterNeed: 'moderate',
    waterNotes: 'Water when soil starts to dry.',
    sunNeed: 'full_sun',
    sunNotes: 'Flowers best in full sun.',
    nutritionNeed: 'low',
    nutritionNotes: 'Avoid rich feeding; too much nitrogen reduces blooms.',
    plantingNotes: 'Deadhead for steady flowers.',
    spacingCm: 25,
    daysToMaturity: 55,
    source: 'system',
    ownerUserId: null,
  },
  {
    commonName: 'Blueberry',
    botanicalName: 'Vaccinium corymbosum',
    plantCategory: 'fruit',
    waterNeed: 'moderate',
    waterNotes: 'Keep soil consistently moist but not waterlogged.',
    sunNeed: 'full_sun',
    sunNotes: 'Full sun gives best fruiting.',
    nutritionNeed: 'moderate',
    nutritionNotes: 'Use acid-loving plant fertilizer in early spring and after bloom.',
    plantingNotes: 'Needs acidic soil and mulch to keep roots cool.',
    spacingCm: 120,
    daysToMaturity: null,
    source: 'system',
    ownerUserId: null,
  },
];

async function up(db: Kysely<Database>) {
  await db.schema
    .createTable('plantLibrary')
    .addColumn('plantLibraryId', 'integer', (col) => col.primaryKey().autoIncrement())
    .addColumn('commonName', 'text', (col) => col.notNull())
    .addColumn('botanicalName', 'text')
    .addColumn('plantCategory', 'text', (col) =>
      col.notNull().check(sql`plantCategory IN ('vegetable', 'fruit', 'herb', 'flower')`),
    )
    .addColumn('waterNeed', 'text', (col) =>
      col.notNull().check(sql`waterNeed IN ('low', 'moderate', 'high')`),
    )
    .addColumn('waterNotes', 'text', (col) => col.notNull())
    .addColumn('sunNeed', 'text', (col) =>
      col.notNull().check(sql`sunNeed IN ('full_sun', 'partial_sun', 'partial_shade')`),
    )
    .addColumn('sunNotes', 'text', (col) => col.notNull())
    .addColumn('nutritionNeed', 'text', (col) =>
      col.notNull().check(sql`nutritionNeed IN ('low', 'moderate', 'high')`),
    )
    .addColumn('nutritionNotes', 'text', (col) => col.notNull())
    .addColumn('plantingNotes', 'text', (col) => col.notNull())
    .addColumn('spacingCm', 'real')
    .addColumn('daysToMaturity', 'integer')
    .addColumn('source', 'text', (col) =>
      col
        .notNull()
        .defaultTo('system')
        .check(sql`source IN ('system', 'user')`),
    )
    .addColumn('ownerUserId', 'integer', (col) =>
      col.references('user.userId').onDelete('set null'),
    )
    .addColumn('createdAt', 'text', (col) => col.defaultTo(sql`CURRENT_TIMESTAMP`).notNull())
    .addColumn('updatedAt', 'text', (col) => col.defaultTo(sql`CURRENT_TIMESTAMP`).notNull())
    .execute();

  await db.schema
    .createIndex('plant_library_common_name_index')
    .on('plantLibrary')
    .column('commonName')
    .execute();

  await db.schema
    .createIndex('plant_library_category_index')
    .on('plantLibrary')
    .column('plantCategory')
    .execute();

  await db.insertInto('plantLibrary').values(plantLibrarySeed).execute();

  await db.schema
    .alterTable('plant')
    .addColumn('plantLibraryId', 'integer', (col) =>
      col.references('plantLibrary.plantLibraryId').onDelete('set null'),
    )
    .execute();
}

async function down(db: Kysely<Database>) {
  await db.schema.alterTable('plant').dropColumn('plantLibraryId').execute();
  await db.schema.dropTable('plantLibrary').execute();
}

export const migration003 = {
  up,
  down,
};
